--
-- PostgreSQL database dump
--

\restrict umx0nVCTKL2wWQJooLcVUA0jAjTub31pNQ1wamca1hiinroECLVuRHaSubSCbzS

-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AlertDeliveries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AlertDeliveries" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "AlertType" integer NOT NULL,
    "Subject" character varying(200) NOT NULL,
    "Body" character varying(4000) NOT NULL,
    "SentAt" timestamp with time zone NOT NULL,
    "Channel" character varying(40) NOT NULL
);


--
-- Name: AlertDeliveries_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AlertDeliveries" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AlertDeliveries_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AlertPreferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AlertPreferences" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "AlertType" integer NOT NULL,
    "Enabled" boolean NOT NULL
);


--
-- Name: AlertPreferences_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AlertPreferences" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AlertPreferences_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: BomItems; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."BomItems" (
    "Id" integer NOT NULL,
    "ProductName" character varying(80) NOT NULL,
    "MaterialId" integer NOT NULL,
    "QuantityPerUnit" numeric(18,2) NOT NULL,
    "Unit" integer NOT NULL
);


--
-- Name: BomItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."BomItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."BomItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Fichas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Fichas" (
    "Id" integer NOT NULL,
    "FichaCode" character varying(30) NOT NULL,
    "ProcessName" text NOT NULL,
    "InstructorName" text NOT NULL,
    "Turno" character varying(20) NOT NULL,
    "InstructorUserId" integer,
    "ProductionOrderId" integer
);


--
-- Name: Fichas_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Fichas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Fichas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: FunctionalRequirements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."FunctionalRequirements" (
    "Id" integer NOT NULL,
    "Code" character varying(10) NOT NULL,
    "Description" text NOT NULL,
    "Module" text NOT NULL,
    "Status" integer NOT NULL,
    "Observation" text NOT NULL
);


--
-- Name: FunctionalRequirements_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."FunctionalRequirements" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FunctionalRequirements_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: MaterialRequests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."MaterialRequests" (
    "Id" integer NOT NULL,
    "MaterialId" integer NOT NULL,
    "Quantity" numeric(18,2) NOT NULL,
    "ProductionOrderId" integer NOT NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


--
-- Name: MaterialRequests_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."MaterialRequests" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."MaterialRequests_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Materials" (
    "Id" integer NOT NULL,
    "Code" character varying(40) NOT NULL,
    "Name" character varying(120) NOT NULL,
    "Unit" integer NOT NULL,
    "Stock" numeric(18,2) NOT NULL,
    "MinStock" numeric(18,2) NOT NULL,
    "Status" integer NOT NULL,
    "LastEntryDate" date NOT NULL
);


--
-- Name: Materials_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Materials" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Materials_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: NonFunctionalRequirements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."NonFunctionalRequirements" (
    "Id" integer NOT NULL,
    "Code" character varying(10) NOT NULL,
    "Description" text NOT NULL,
    "Status" integer NOT NULL,
    "Observation" text NOT NULL
);


--
-- Name: NonFunctionalRequirements_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."NonFunctionalRequirements" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."NonFunctionalRequirements_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PasswordResetTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."PasswordResetTokens" (
    "Id" integer NOT NULL,
    "UserId" integer NOT NULL,
    "TokenHash" character varying(128) NOT NULL,
    "ExpiresAtUtc" timestamp with time zone NOT NULL,
    "UsedAtUtc" timestamp with time zone,
    "CreatedAtUtc" timestamp with time zone NOT NULL
);


--
-- Name: PasswordResetTokens_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."PasswordResetTokens" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PasswordResetTokens_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductionOrders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ProductionOrders" (
    "Id" integer NOT NULL,
    "OrderNumber" character varying(20) NOT NULL,
    "ProductName" character varying(80) NOT NULL,
    "TotalQuantity" integer NOT NULL,
    "ProducedQuantity" integer NOT NULL,
    "Status" integer NOT NULL,
    "Deadline" date NOT NULL
);


--
-- Name: ProductionOrders_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ProductionOrders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductionOrders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ProductionSessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ProductionSessions" (
    "Id" integer NOT NULL,
    "FichaId" integer NOT NULL,
    "ProductionOrderId" integer NOT NULL,
    "Units" integer NOT NULL,
    "Observations" character varying(500) NOT NULL,
    "SessionDate" timestamp with time zone NOT NULL,
    "RegisteredByUserId" integer
);


--
-- Name: ProductionSessions_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ProductionSessions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ProductionSessions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: QualityRecords; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."QualityRecords" (
    "Id" integer NOT NULL,
    "ProductionOrderId" integer NOT NULL,
    "UnitsInspected" integer NOT NULL,
    "Result" integer NOT NULL,
    "MotivoReproceso" character varying(300),
    "Responsable" character varying(120),
    "InspectionDate" date NOT NULL
);


--
-- Name: QualityRecords_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."QualityRecords" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."QualityRecords_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Nombre" character varying(120) NOT NULL,
    "Email" character varying(160) NOT NULL,
    "PasswordHash" character varying(256) NOT NULL,
    "Rol" character varying(40) NOT NULL,
    "FichaAsignadaId" integer,
    "PermisosExtendidos" character varying(500) NOT NULL,
    "PhotoPath" character varying(260),
    "FuncionDescripcion" character varying(800),
    "IsActive" boolean NOT NULL
);


--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Name: AlertDeliveries PK_AlertDeliveries; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AlertDeliveries"
    ADD CONSTRAINT "PK_AlertDeliveries" PRIMARY KEY ("Id");


--
-- Name: AlertPreferences PK_AlertPreferences; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AlertPreferences"
    ADD CONSTRAINT "PK_AlertPreferences" PRIMARY KEY ("Id");


--
-- Name: BomItems PK_BomItems; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BomItems"
    ADD CONSTRAINT "PK_BomItems" PRIMARY KEY ("Id");


--
-- Name: Fichas PK_Fichas; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Fichas"
    ADD CONSTRAINT "PK_Fichas" PRIMARY KEY ("Id");


--
-- Name: FunctionalRequirements PK_FunctionalRequirements; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."FunctionalRequirements"
    ADD CONSTRAINT "PK_FunctionalRequirements" PRIMARY KEY ("Id");


--
-- Name: MaterialRequests PK_MaterialRequests; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MaterialRequests"
    ADD CONSTRAINT "PK_MaterialRequests" PRIMARY KEY ("Id");


--
-- Name: Materials PK_Materials; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Materials"
    ADD CONSTRAINT "PK_Materials" PRIMARY KEY ("Id");


--
-- Name: NonFunctionalRequirements PK_NonFunctionalRequirements; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."NonFunctionalRequirements"
    ADD CONSTRAINT "PK_NonFunctionalRequirements" PRIMARY KEY ("Id");


--
-- Name: PasswordResetTokens PK_PasswordResetTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PasswordResetTokens"
    ADD CONSTRAINT "PK_PasswordResetTokens" PRIMARY KEY ("Id");


--
-- Name: ProductionOrders PK_ProductionOrders; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProductionOrders"
    ADD CONSTRAINT "PK_ProductionOrders" PRIMARY KEY ("Id");


--
-- Name: ProductionSessions PK_ProductionSessions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProductionSessions"
    ADD CONSTRAINT "PK_ProductionSessions" PRIMARY KEY ("Id");


--
-- Name: QualityRecords PK_QualityRecords; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."QualityRecords"
    ADD CONSTRAINT "PK_QualityRecords" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_AlertDeliveries_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AlertDeliveries_UserId" ON public."AlertDeliveries" USING btree ("UserId");


--
-- Name: IX_AlertPreferences_UserId_AlertType; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_AlertPreferences_UserId_AlertType" ON public."AlertPreferences" USING btree ("UserId", "AlertType");


--
-- Name: IX_BomItems_MaterialId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_BomItems_MaterialId" ON public."BomItems" USING btree ("MaterialId");


--
-- Name: IX_Fichas_InstructorUserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Fichas_InstructorUserId" ON public."Fichas" USING btree ("InstructorUserId");


--
-- Name: IX_Fichas_ProductionOrderId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Fichas_ProductionOrderId" ON public."Fichas" USING btree ("ProductionOrderId");


--
-- Name: IX_FunctionalRequirements_Code; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_FunctionalRequirements_Code" ON public."FunctionalRequirements" USING btree ("Code");


--
-- Name: IX_MaterialRequests_MaterialId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_MaterialRequests_MaterialId" ON public."MaterialRequests" USING btree ("MaterialId");


--
-- Name: IX_MaterialRequests_ProductionOrderId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_MaterialRequests_ProductionOrderId" ON public."MaterialRequests" USING btree ("ProductionOrderId");


--
-- Name: IX_NonFunctionalRequirements_Code; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_NonFunctionalRequirements_Code" ON public."NonFunctionalRequirements" USING btree ("Code");


--
-- Name: IX_PasswordResetTokens_TokenHash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PasswordResetTokens_TokenHash" ON public."PasswordResetTokens" USING btree ("TokenHash");


--
-- Name: IX_PasswordResetTokens_UserId_CreatedAtUtc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_PasswordResetTokens_UserId_CreatedAtUtc" ON public."PasswordResetTokens" USING btree ("UserId", "CreatedAtUtc");


--
-- Name: IX_ProductionOrders_OrderNumber; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ProductionOrders_OrderNumber" ON public."ProductionOrders" USING btree ("OrderNumber");


--
-- Name: IX_ProductionSessions_FichaId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ProductionSessions_FichaId" ON public."ProductionSessions" USING btree ("FichaId");


--
-- Name: IX_ProductionSessions_ProductionOrderId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ProductionSessions_ProductionOrderId" ON public."ProductionSessions" USING btree ("ProductionOrderId");


--
-- Name: IX_ProductionSessions_RegisteredByUserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ProductionSessions_RegisteredByUserId" ON public."ProductionSessions" USING btree ("RegisteredByUserId");


--
-- Name: IX_QualityRecords_ProductionOrderId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_QualityRecords_ProductionOrderId" ON public."QualityRecords" USING btree ("ProductionOrderId");


--
-- Name: IX_Users_Email; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Users_Email" ON public."Users" USING btree ("Email");


--
-- Name: IX_Users_FichaAsignadaId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Users_FichaAsignadaId" ON public."Users" USING btree ("FichaAsignadaId");


--
-- Name: AlertDeliveries FK_AlertDeliveries_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AlertDeliveries"
    ADD CONSTRAINT "FK_AlertDeliveries_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: AlertPreferences FK_AlertPreferences_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AlertPreferences"
    ADD CONSTRAINT "FK_AlertPreferences_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: BomItems FK_BomItems_Materials_MaterialId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."BomItems"
    ADD CONSTRAINT "FK_BomItems_Materials_MaterialId" FOREIGN KEY ("MaterialId") REFERENCES public."Materials"("Id") ON DELETE CASCADE;


--
-- Name: Fichas FK_Fichas_ProductionOrders_ProductionOrderId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Fichas"
    ADD CONSTRAINT "FK_Fichas_ProductionOrders_ProductionOrderId" FOREIGN KEY ("ProductionOrderId") REFERENCES public."ProductionOrders"("Id");


--
-- Name: Fichas FK_Fichas_Users_InstructorUserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Fichas"
    ADD CONSTRAINT "FK_Fichas_Users_InstructorUserId" FOREIGN KEY ("InstructorUserId") REFERENCES public."Users"("Id") ON DELETE SET NULL;


--
-- Name: MaterialRequests FK_MaterialRequests_Materials_MaterialId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MaterialRequests"
    ADD CONSTRAINT "FK_MaterialRequests_Materials_MaterialId" FOREIGN KEY ("MaterialId") REFERENCES public."Materials"("Id") ON DELETE CASCADE;


--
-- Name: MaterialRequests FK_MaterialRequests_ProductionOrders_ProductionOrderId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."MaterialRequests"
    ADD CONSTRAINT "FK_MaterialRequests_ProductionOrders_ProductionOrderId" FOREIGN KEY ("ProductionOrderId") REFERENCES public."ProductionOrders"("Id") ON DELETE CASCADE;


--
-- Name: PasswordResetTokens FK_PasswordResetTokens_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."PasswordResetTokens"
    ADD CONSTRAINT "FK_PasswordResetTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: ProductionSessions FK_ProductionSessions_Fichas_FichaId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProductionSessions"
    ADD CONSTRAINT "FK_ProductionSessions_Fichas_FichaId" FOREIGN KEY ("FichaId") REFERENCES public."Fichas"("Id") ON DELETE CASCADE;


--
-- Name: ProductionSessions FK_ProductionSessions_ProductionOrders_ProductionOrderId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProductionSessions"
    ADD CONSTRAINT "FK_ProductionSessions_ProductionOrders_ProductionOrderId" FOREIGN KEY ("ProductionOrderId") REFERENCES public."ProductionOrders"("Id") ON DELETE CASCADE;


--
-- Name: ProductionSessions FK_ProductionSessions_Users_RegisteredByUserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ProductionSessions"
    ADD CONSTRAINT "FK_ProductionSessions_Users_RegisteredByUserId" FOREIGN KEY ("RegisteredByUserId") REFERENCES public."Users"("Id") ON DELETE SET NULL;


--
-- Name: QualityRecords FK_QualityRecords_ProductionOrders_ProductionOrderId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."QualityRecords"
    ADD CONSTRAINT "FK_QualityRecords_ProductionOrders_ProductionOrderId" FOREIGN KEY ("ProductionOrderId") REFERENCES public."ProductionOrders"("Id") ON DELETE CASCADE;


--
-- Name: Users FK_Users_Fichas_FichaAsignadaId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "FK_Users_Fichas_FichaAsignadaId" FOREIGN KEY ("FichaAsignadaId") REFERENCES public."Fichas"("Id") ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--

\unrestrict umx0nVCTKL2wWQJooLcVUA0jAjTub31pNQ1wamca1hiinroECLVuRHaSubSCbzS

