// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sipitex.Infrastructure.Persistence;

#nullable disable

namespace Sipitex.Infrastructure.Migrations
{
    [DbContext(typeof(SipitexDbContext))]
    [Migration("20260917022019_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sipitex.Domain.Entities.ActaMovimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("EntregaCargo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("EntregaConformidadUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EntregaFirmaPng")
                        .HasColumnType("bytea");

                    b.Property<string>("EntregaNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("EstadoProductoDestino")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("EstadoProductoOrigen")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("RecibeCargo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime?>("RecibeConformidadUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RecibeFirmaPng")
                        .HasColumnType("bytea");

                    b.Property<string>("RecibeNombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorUserId");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("ActasMovimiento", (string)null);
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ActaMovimientoDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActaMovimientoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<int?>("ConsumoMaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("ItemTipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("StockMovementId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidad")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ActaMovimientoId");

                    b.HasIndex("ConsumoMaterialId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("StockMovementId");

                    b.ToTable("ActasMovimientoDetalle", (string)null);
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("EntityId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertType")
                        .HasColumnType("integer");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AlertDeliveries");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlertType")
                        .HasColumnType("integer");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AlertType")
                        .IsUnique();

                    b.ToTable("AlertPreferences");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BomProductId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BomProductId");

                    b.HasIndex("MaterialId");

                    b.ToTable("BomItems");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnioMuestrario")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("DescripcionPrenda")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Digitacion")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Disenador")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("EsBancoDeMuestras")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsDisenoNuevo")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsReplica")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("FechaElaboracion")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaSolicitud")
                        .HasColumnType("date");

                    b.Property<bool>("HabilitadoParaOrdenes")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsReference")
                        .HasColumnType("boolean");

                    b.Property<string>("Linea")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Patronista")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TallaInicial")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TipoEmpaque")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("BomProducts");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductInstructor", b =>
                {
                    b.Property<int>("BomProductId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BomProductId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("BomProductInstructors");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BomProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ComoMedir")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Tolerancia")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("BomProductId");

                    b.HasIndex("BomProductId", "Tipo", "Orden");

                    b.ToTable("BomProductMedidas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductMedidaValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BomProductMedidaId")
                        .HasColumnType("integer");

                    b.Property<int>("BomProductTallaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BomProductTallaId");

                    b.HasIndex("BomProductMedidaId", "BomProductTallaId")
                        .IsUnique();

                    b.ToTable("BomProductMedidaValores");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductPieza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BomProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<string>("Tela")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("BomProductId");

                    b.HasIndex("BomProductId", "Orden");

                    b.ToTable("BomProductPiezas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductTalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BomProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BomProductId");

                    b.HasIndex("BomProductId", "Orden");

                    b.ToTable("BomProductTallas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ConsumoMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CostoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GrupoConfeccionId")
                        .HasColumnType("integer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsableUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("GrupoConfeccionId");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("ResponsableUserId");

                    b.ToTable("ConsumosMaterial");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.DetalleSolicitudMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CantidadAprobada")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("CantidadSolicitada")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("DescripcionItem")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EstadoItem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitudMaterialId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SolicitudMaterialId");

                    b.ToTable("DetallesSolicitudMaterial");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.EntregaMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("EncargadoDeBodegaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SolicitudMaterialId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EncargadoDeBodegaId");

                    b.HasIndex("SolicitudMaterialId")
                        .IsUnique();

                    b.ToTable("EntregasMaterial");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Ficha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedOrderText")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("InstructorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroGrupo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorUserId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("Fichas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FichaInstructor", b =>
                {
                    b.Property<int>("FichaId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Proceso")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.HasKey("FichaId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FichaInstructors");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FinishedGoodMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("StageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ProductName");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("FinishedGoodMovements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FinishedGoodStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Stock")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("FinishedGoodStocks");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FunctionalRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FunctionalRequirements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.GrupoConfeccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadPrendas")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("FechaRealizacion")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<int>("InstructorUserId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FechaRealizacion");

                    b.HasIndex("InstructorUserId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("GruposConfeccion");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.InstructorStagePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StageName")
                        .IsUnique();

                    b.ToTable("InstructorStagePermissions");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("CostoAdquisicion")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateOnly>("LastEntryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("MinStock")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("PlantaInventarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("Stock")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlantaInventarioId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.MaterialRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("SolicitanteId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("MaterialRequests");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.NonFunctionalRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("NonFunctionalRequirements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.OrderChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("OrderChangeLogs");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.PlantaInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.ToTable("PlantasInventario");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Nombre = "Planta de Inventario 1"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Nombre = "Planta de Inventario 2"
                        });
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.PrendaTrazable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("CreadoPorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreadoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Talla")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("CreadoPorUserId");

                    b.HasIndex("CreadoUtc");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("PrendasTrazables", (string)null);
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductFlowStageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("ProductFlowTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductFlowTemplateId", "SortOrder");

                    b.ToTable("ProductFlowStageTemplates");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductFlowTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ProductName");

                    b.ToTable("ProductFlowTemplates");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int?>("CurrentStageId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("date");

                    b.Property<string>("EstadoProducto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("MaterialsStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("integer");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderBomSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("ProductionOrderBomSnapshots");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ActorUserName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("StageId")
                        .HasColumnType("integer");

                    b.Property<string>("StageName")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId", "AtUtc");

                    b.ToTable("ProductionOrderHistoryEntries");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderMaterialRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantityDelivered")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("QuantityRequired")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Unit")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("ProductionOrderId", "MaterialId")
                        .IsUnique();

                    b.ToTable("ProductionOrderMaterialRequirements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InstructorUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityProcessed")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("integer");

                    b.Property<int>("QuantitySent")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityWithdrawn")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorUserId");

                    b.HasIndex("ProductionOrderId", "SortOrder");

                    b.ToTable("ProductionOrderStages");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderStageMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AuthorizedByUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("FromStageId")
                        .HasColumnType("integer");

                    b.Property<string>("Motive")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("ToStageId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("AuthorizedByUserId");

                    b.HasIndex("FromStageId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("ToStageId");

                    b.ToTable("ProductionOrderStageMovements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FichaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("RegisteredByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Units")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("RegisteredByUserId");

                    b.ToTable("ProductionSessions");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.QualityRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clasificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("date");

                    b.Property<string>("MotivoReproceso")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<string>("Responsable")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("UnitsInspected")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("QualityRecords");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.SolicitudMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DescripcionLibre")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FichaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("PlantaInventarioId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("integer");

                    b.Property<int?>("ResueltoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("PorFicha");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FichaId");

                    b.HasIndex("PlantaInventarioId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("ResueltoPorId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("Tipo");

                    b.ToTable("SolicitudesMaterial");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("CostoUnitario")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer");

                    b.Property<string>("Origen")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Referencia")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<decimal>("StockResultante")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int?>("FichaAsignadaId")
                        .HasColumnType("integer");

                    b.Property<string>("FuncionDescripcion")
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PermisosExtendidos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FichaAsignadaId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.UserPlantaInventario", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("PlantaInventarioId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "PlantaInventarioId");

                    b.HasIndex("PlantaInventarioId");

                    b.ToTable("UserPlantasInventario");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ActaMovimiento", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreadoPor");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ActaMovimientoDetalle", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ActaMovimiento", "ActaMovimiento")
                        .WithMany("Detalles")
                        .HasForeignKey("ActaMovimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ConsumoMaterial", "ConsumoMaterial")
                        .WithMany()
                        .HasForeignKey("ConsumoMaterialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.StockMovement", "StockMovement")
                        .WithMany()
                        .HasForeignKey("StockMovementId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActaMovimiento");

                    b.Navigation("ConsumoMaterial");

                    b.Navigation("Material");

                    b.Navigation("ProductionOrder");

                    b.Navigation("StockMovement");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertDelivery", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertPreference", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomItem", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProduct", "BomProduct")
                        .WithMany("Items")
                        .HasForeignKey("BomProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany("BomItems")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomProduct");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductInstructor", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProduct", "BomProduct")
                        .WithMany("Instructors")
                        .HasForeignKey("BomProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomProduct");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductMedida", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProduct", "BomProduct")
                        .WithMany("Medidas")
                        .HasForeignKey("BomProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomProduct");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductMedidaValor", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProductMedida", "Medida")
                        .WithMany("Valores")
                        .HasForeignKey("BomProductMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.BomProductTalla", "Talla")
                        .WithMany("MedidaValores")
                        .HasForeignKey("BomProductTallaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medida");

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductPieza", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProduct", "BomProduct")
                        .WithMany("Piezas")
                        .HasForeignKey("BomProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomProduct");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductTalla", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProduct", "BomProduct")
                        .WithMany("Tallas")
                        .HasForeignKey("BomProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomProduct");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ConsumoMaterial", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.GrupoConfeccion", "GrupoConfeccion")
                        .WithMany("Consumos")
                        .HasForeignKey("GrupoConfeccionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany("Consumos")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("Consumos")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "Responsable")
                        .WithMany()
                        .HasForeignKey("ResponsableUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoConfeccion");

                    b.Navigation("Material");

                    b.Navigation("ProductionOrder");

                    b.Navigation("Responsable");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.DetalleSolicitudMaterial", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sipitex.Domain.Entities.SolicitudMaterial", "SolicitudMaterial")
                        .WithMany("Detalles")
                        .HasForeignKey("SolicitudMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("SolicitudMaterial");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.EntregaMaterial", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "EncargadoDeBodega")
                        .WithMany()
                        .HasForeignKey("EncargadoDeBodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.SolicitudMaterial", "SolicitudMaterial")
                        .WithOne("Entrega")
                        .HasForeignKey("Sipitex.Domain.Entities.EntregaMaterial", "SolicitudMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncargadoDeBodega");

                    b.Navigation("SolicitudMaterial");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Ficha", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "InstructorUser")
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("Fichas")
                        .HasForeignKey("ProductionOrderId");

                    b.Navigation("InstructorUser");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FichaInstructor", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Ficha", "Ficha")
                        .WithMany("Instructors")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ficha");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FinishedGoodMovement", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.GrupoConfeccion", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("GruposConfeccion")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.InstructorStagePermission", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Material", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.PlantaInventario", "PlantaInventario")
                        .WithMany("Materiales")
                        .HasForeignKey("PlantaInventarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantaInventario");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.MaterialRequest", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany("Requests")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("MaterialRequests")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Material");

                    b.Navigation("ProductionOrder");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.OrderChangeLog", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.PrendaTrazable", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("PrendasTrazables")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductFlowStageTemplate", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ProductFlowTemplate", "Template")
                        .WithMany("Stages")
                        .HasForeignKey("ProductFlowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrder", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ProductionOrderStage", "CurrentStage")
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentStage");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderBomSnapshot", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("BomSnapshots")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderHistoryEntry", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderMaterialRequirement", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("MaterialRequirements")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderStage", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "InstructorUser")
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("Stages")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructorUser");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderStageMovement", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "AuthorizedByUser")
                        .WithMany()
                        .HasForeignKey("AuthorizedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrderStage", "FromStage")
                        .WithMany()
                        .HasForeignKey("FromStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("StageMovements")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrderStage", "ToStage")
                        .WithMany()
                        .HasForeignKey("ToStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("AuthorizedByUser");

                    b.Navigation("FromStage");

                    b.Navigation("ProductionOrder");

                    b.Navigation("ToStage");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionSession", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Ficha", "Ficha")
                        .WithMany()
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "RegisteredByUser")
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ficha");

                    b.Navigation("ProductionOrder");

                    b.Navigation("RegisteredByUser");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.QualityRecord", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("QualityRecords")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.SolicitudMaterial", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Ficha", "Ficha")
                        .WithMany()
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sipitex.Domain.Entities.PlantaInventario", "PlantaInventario")
                        .WithMany("Solicitudes")
                        .HasForeignKey("PlantaInventarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.User", "ResueltoPor")
                        .WithMany()
                        .HasForeignKey("ResueltoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.User", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ficha");

                    b.Navigation("PlantaInventario");

                    b.Navigation("ProductionOrder");

                    b.Navigation("ResueltoPor");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany("StockMovements")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.User", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Ficha", "FichaAsignada")
                        .WithMany()
                        .HasForeignKey("FichaAsignadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FichaAsignada");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.UserPlantaInventario", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.PlantaInventario", "PlantaInventario")
                        .WithMany("Encargados")
                        .HasForeignKey("PlantaInventarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany("UserPlantasInventario")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlantaInventario");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ActaMovimiento", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProduct", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Items");

                    b.Navigation("Medidas");

                    b.Navigation("Piezas");

                    b.Navigation("Tallas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductMedida", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductTalla", b =>
                {
                    b.Navigation("MedidaValores");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Ficha", b =>
                {
                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.GrupoConfeccion", b =>
                {
                    b.Navigation("Consumos");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Material", b =>
                {
                    b.Navigation("BomItems");

                    b.Navigation("Consumos");

                    b.Navigation("Requests");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.PlantaInventario", b =>
                {
                    b.Navigation("Encargados");

                    b.Navigation("Materiales");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductFlowTemplate", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrder", b =>
                {
                    b.Navigation("BomSnapshots");

                    b.Navigation("ChangeLogs");

                    b.Navigation("Consumos");

                    b.Navigation("Fichas");

                    b.Navigation("GruposConfeccion");

                    b.Navigation("HistoryEntries");

                    b.Navigation("MaterialRequests");

                    b.Navigation("MaterialRequirements");

                    b.Navigation("PrendasTrazables");

                    b.Navigation("QualityRecords");

                    b.Navigation("StageMovements");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.SolicitudMaterial", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.User", b =>
                {
                    b.Navigation("UserPlantasInventario");
                });
#pragma warning restore 612, 618
        }
    }
}
