// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sipitex.Infrastructure.Persistence;

#nullable disable

namespace Sipitex.Infrastructure.Migrations
{
    [DbContext(typeof(SipitexDbContext))]
    [Migration("20260820125344_AddUserBodegas")]
    partial class AddUserBodegas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Sipitex.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityId")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AlertDeliveries");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AlertType")
                        .IsUnique();

                    b.ToTable("AlertPreferences");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Bodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bodegas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Bodega 1"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Bodega 2"
                        });
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BomProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BomProductId");

                    b.HasIndex("MaterialId");

                    b.ToTable("BomItems");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnioMuestrario")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DescripcionPrenda")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Digitacion")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Disenador")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsBancoDeMuestras")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsDisenoNuevo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsReplica")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("FechaElaboracion")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("FechaSolicitud")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HabilitadoParaOrdenes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReference")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Linea")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronista")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TallaInicial")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEmpaque")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("BomProducts");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductInstructor", b =>
                {
                    b.Property<int>("BomProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("BomProductId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("BomProductInstructors");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BomProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ComoMedir")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tolerancia")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BomProductId");

                    b.HasIndex("BomProductId", "Tipo", "Orden");

                    b.ToTable("BomProductMedidas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductMedidaValor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BomProductMedidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BomProductTallaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BomProductTallaId");

                    b.HasIndex("BomProductMedidaId", "BomProductTallaId")
                        .IsUnique();

                    b.ToTable("BomProductMedidaValores");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductPieza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BomProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tela")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BomProductId");

                    b.HasIndex("BomProductId", "Orden");

                    b.ToTable("BomProductPiezas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductTalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BomProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("Orden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BomProductId");

                    b.HasIndex("BomProductId", "Orden");

                    b.ToTable("BomProductTallas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.DetalleSolicitudMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CantidadAprobada")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CantidadSolicitada")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionItem")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoItem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SolicitudMaterialId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("SolicitudMaterialId");

                    b.ToTable("DetallesSolicitudMaterial");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.EntregaMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodegueroId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("SolicitudMaterialId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BodegueroId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("SolicitudMaterialId")
                        .IsUnique();

                    b.ToTable("EntregasMaterial");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Ficha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssignedOrderText")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FichaCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstructorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstructorUserId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("Fichas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FichaInstructor", b =>
                {
                    b.Property<int>("FichaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Proceso")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("FichaId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FichaInstructors");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FinishedGoodMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ProductName");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("FinishedGoodMovements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FinishedGoodStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Stock")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("FinishedGoodStocks");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FunctionalRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FunctionalRequirements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.InstructorStagePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "StageName")
                        .IsUnique();

                    b.ToTable("InstructorStagePermissions");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodegaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LastEntryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinStock")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Stock")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BodegaId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.MaterialRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SolicitanteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("MaterialRequests");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.NonFunctionalRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("NonFunctionalRequirements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.OrderChangeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("OrderChangeLogs");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductFlowStageTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductFlowTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductFlowTemplateId", "SortOrder");

                    b.ToTable("ProductFlowStageTemplates");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductFlowTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductName");

                    b.ToTable("ProductFlowTemplates");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentStageId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialsStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStageId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderBomSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("ProductionOrderBomSnapshots");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActorUserName")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageName")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId", "AtUtc");

                    b.ToTable("ProductionOrderHistoryEntries");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderMaterialRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("QuantityDelivered")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityRequired")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("ProductionOrderId", "MaterialId")
                        .IsUnique();

                    b.ToTable("ProductionOrderMaterialRequirements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstructorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantitySent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantityWithdrawn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstructorUserId");

                    b.HasIndex("ProductionOrderId", "SortOrder");

                    b.ToTable("ProductionOrderStages");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderStageMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("AuthorizedByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FromStageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motive")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observations")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ToStageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("AuthorizedByUserId");

                    b.HasIndex("FromStageId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("ToStageId");

                    b.ToTable("ProductionOrderStageMovements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FichaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RegisteredByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Units")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("RegisteredByUserId");

                    b.ToTable("ProductionSessions");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.QualityRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoReproceso")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsable")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitsInspected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("QualityRecords");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.SolicitudMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodegaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescripcionLibre")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FichaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResueltoPorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BodegaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FichaId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("ResueltoPorId");

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("Tipo");

                    b.ToTable("SolicitudesMaterial");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Origen")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StockResultante")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FechaUtc");

                    b.HasIndex("MaterialId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FichaAsignadaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuncionDescripcion")
                        .HasMaxLength(800)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PermisosExtendidos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoPath")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FichaAsignadaId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.UserBodega", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BodegaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "BodegaId");

                    b.HasIndex("BodegaId");

                    b.ToTable("UserBodegas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertDelivery", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertPreference", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomItem", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProduct", "BomProduct")
                        .WithMany("Items")
                        .HasForeignKey("BomProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany("BomItems")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomProduct");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductInstructor", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProduct", "BomProduct")
                        .WithMany("Instructors")
                        .HasForeignKey("BomProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomProduct");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductMedida", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProduct", "BomProduct")
                        .WithMany("Medidas")
                        .HasForeignKey("BomProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomProduct");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductMedidaValor", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProductMedida", "Medida")
                        .WithMany("Valores")
                        .HasForeignKey("BomProductMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.BomProductTalla", "Talla")
                        .WithMany("MedidaValores")
                        .HasForeignKey("BomProductTallaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medida");

                    b.Navigation("Talla");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductPieza", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProduct", "BomProduct")
                        .WithMany("Piezas")
                        .HasForeignKey("BomProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomProduct");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductTalla", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.BomProduct", "BomProduct")
                        .WithMany("Tallas")
                        .HasForeignKey("BomProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomProduct");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.DetalleSolicitudMaterial", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sipitex.Domain.Entities.SolicitudMaterial", "SolicitudMaterial")
                        .WithMany("Detalles")
                        .HasForeignKey("SolicitudMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("SolicitudMaterial");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.EntregaMaterial", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "Bodeguero")
                        .WithMany()
                        .HasForeignKey("BodegueroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.SolicitudMaterial", "SolicitudMaterial")
                        .WithOne("Entrega")
                        .HasForeignKey("Sipitex.Domain.Entities.EntregaMaterial", "SolicitudMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodeguero");

                    b.Navigation("SolicitudMaterial");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Ficha", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "InstructorUser")
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("Fichas")
                        .HasForeignKey("ProductionOrderId");

                    b.Navigation("InstructorUser");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FichaInstructor", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Ficha", "Ficha")
                        .WithMany("Instructors")
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ficha");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FinishedGoodMovement", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActorUser");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.InstructorStagePermission", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Material", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Bodega", "Bodega")
                        .WithMany("Materiales")
                        .HasForeignKey("BodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bodega");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.MaterialRequest", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany("Requests")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("MaterialRequests")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Material");

                    b.Navigation("ProductionOrder");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.OrderChangeLog", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("ChangeLogs")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductionOrder");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductFlowStageTemplate", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ProductFlowTemplate", "Template")
                        .WithMany("Stages")
                        .HasForeignKey("ProductFlowTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrder", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ProductionOrderStage", "CurrentStage")
                        .WithMany()
                        .HasForeignKey("CurrentStageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentStage");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderBomSnapshot", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("BomSnapshots")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderHistoryEntry", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("HistoryEntries")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderMaterialRequirement", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("MaterialRequirements")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderStage", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "InstructorUser")
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("Stages")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InstructorUser");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrderStageMovement", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "AuthorizedByUser")
                        .WithMany()
                        .HasForeignKey("AuthorizedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrderStage", "FromStage")
                        .WithMany()
                        .HasForeignKey("FromStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("StageMovements")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrderStage", "ToStage")
                        .WithMany()
                        .HasForeignKey("ToStageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActorUser");

                    b.Navigation("AuthorizedByUser");

                    b.Navigation("FromStage");

                    b.Navigation("ProductionOrder");

                    b.Navigation("ToStage");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionSession", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Ficha", "Ficha")
                        .WithMany()
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "RegisteredByUser")
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ficha");

                    b.Navigation("ProductionOrder");

                    b.Navigation("RegisteredByUser");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.QualityRecord", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("QualityRecords")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.SolicitudMaterial", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Bodega", "Bodega")
                        .WithMany("Solicitudes")
                        .HasForeignKey("BodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.Ficha", "Ficha")
                        .WithMany()
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.User", "ResueltoPor")
                        .WithMany()
                        .HasForeignKey("ResueltoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.User", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("Ficha");

                    b.Navigation("ProductionOrder");

                    b.Navigation("ResueltoPor");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany("StockMovements")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.User", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Ficha", "FichaAsignada")
                        .WithMany()
                        .HasForeignKey("FichaAsignadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FichaAsignada");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.UserBodega", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Bodega", "Bodega")
                        .WithMany("Bodegueros")
                        .HasForeignKey("BodegaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany("UserBodegas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bodega");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Bodega", b =>
                {
                    b.Navigation("Bodegueros");

                    b.Navigation("Materiales");

                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProduct", b =>
                {
                    b.Navigation("Instructors");

                    b.Navigation("Items");

                    b.Navigation("Medidas");

                    b.Navigation("Piezas");

                    b.Navigation("Tallas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductMedida", b =>
                {
                    b.Navigation("Valores");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomProductTalla", b =>
                {
                    b.Navigation("MedidaValores");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Ficha", b =>
                {
                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Material", b =>
                {
                    b.Navigation("BomItems");

                    b.Navigation("Requests");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductFlowTemplate", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrder", b =>
                {
                    b.Navigation("BomSnapshots");

                    b.Navigation("ChangeLogs");

                    b.Navigation("Fichas");

                    b.Navigation("HistoryEntries");

                    b.Navigation("MaterialRequests");

                    b.Navigation("MaterialRequirements");

                    b.Navigation("QualityRecords");

                    b.Navigation("StageMovements");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.SolicitudMaterial", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Entrega");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.User", b =>
                {
                    b.Navigation("UserBodegas");
                });
#pragma warning restore 612, 618
        }
    }
}
