// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sipitex.Infrastructure.Persistence;

#nullable disable

namespace Sipitex.Infrastructure.Migrations
{
    [DbContext(typeof(SipitexDbContext))]
    partial class SipitexDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AlertDeliveries");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertType")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "AlertType")
                        .IsUnique();

                    b.ToTable("AlertPreferences");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("QuantityPerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("BomItems");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Ficha", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FichaCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("InstructorName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("InstructorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstructorUserId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("Fichas");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.FunctionalRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("FunctionalRequirements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("LastEntryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinStock")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Stock")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Unit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.MaterialRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaterialId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("MaterialRequests");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.NonFunctionalRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("NonFunctionalRequirements");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Deadline")
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProducedQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("ProductionOrders");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FichaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RegisteredByUserId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SessionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Units")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FichaId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("RegisteredByUserId");

                    b.ToTable("ProductionSessions");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.QualityRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("InspectionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoReproceso")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductionOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Responsable")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("Result")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitsInspected")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("QualityRecords");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FichaAsignadaId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PermisosExtendidos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FichaAsignadaId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertDelivery", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.AlertPreference", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.BomItem", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany("BomItems")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Ficha", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "InstructorUser")
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("Fichas")
                        .HasForeignKey("ProductionOrderId");

                    b.Navigation("InstructorUser");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.MaterialRequest", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Material", "Material")
                        .WithMany("Requests")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("MaterialRequests")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionSession", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Ficha", "Ficha")
                        .WithMany()
                        .HasForeignKey("FichaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany()
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sipitex.Domain.Entities.User", "RegisteredByUser")
                        .WithMany()
                        .HasForeignKey("RegisteredByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ficha");

                    b.Navigation("ProductionOrder");

                    b.Navigation("RegisteredByUser");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.QualityRecord", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("QualityRecords")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.User", b =>
                {
                    b.HasOne("Sipitex.Domain.Entities.Ficha", "FichaAsignada")
                        .WithMany()
                        .HasForeignKey("FichaAsignadaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FichaAsignada");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.Material", b =>
                {
                    b.Navigation("BomItems");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Sipitex.Domain.Entities.ProductionOrder", b =>
                {
                    b.Navigation("Fichas");

                    b.Navigation("MaterialRequests");

                    b.Navigation("QualityRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
